version: "3.8"
name: crud

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: crud_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api_instance_1:
    image: crud:latest
    ports: 
      - "3000"
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/crud_db
      INSTANCE_NAME: Server1
    depends_on:
      - postgres
    
  api_instance_2:
    image: crud:latest
    ports: 
      - "3000"
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/crud_db
      INSTANCE_NAME: Server2
    depends_on:
      - postgres
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_instance_1
      - api_instance_2


volumes:
  pgdata:
