version: "3.8"
name: crud

services:
  postgres:
    image: postgres:17-alpine
    env_file:
      - ./../conf/.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api_instance_1:
    image: crud:latest
    ports:
      - "3000"
    environment:
      INSTANCE_NAME: Server1
    env_file:
      - ./../conf/.env
    depends_on:
      - postgres

  api_instance_2:
    image: crud:latest
    ports:
      - "3000"
    environment:
      INSTANCE_NAME: Server2
    env_file:
      - ./../conf/.env
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_instance_1
      - api_instance_2

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    depends_on:
      - nginx
      - api_instance_1
      - api_instance_2

volumes:
  pgdata:
