version: "3.8"
name: crud

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: info_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    image: crud:latest
    ports: 
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/crud_db
    depends_on:
      - postgres

volumes:
  pgdata:
